networks:
  pingpong:
    name: pingpong
    driver: bridge

services:
  postgresql:
    container_name: postgresql
    build: ./postgresql
    image: postgresql:pingpong
    networks:
      - pingpong
    env_file:
      - ./.env
    restart: on-failure

  django-wsgi:
    container_name: django-wsgi
    build: 
      context: ./django
      dockerfile: wsgi/Dockerfile
    image: django-wsgi:pingpong
    networks:
      - pingpong
    env_file:
      - ./.env
    depends_on:
      - postgresql
    restart: on-failure


  django-asgi:
    container_name: django-asgi
    build:
      context: ./django
      dockerfile: asgi/Dockerfile
    image: django-asgi:pingpong
    networks:
      - pingpong
    env_file:
      - ./.env
    depends_on:
      - postgresql
      - django-wsgi
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx:pingpong
    networks:
      - pingpong
    env_file:
      - ./.env
    depends_on:
      - postgresql
      - django-wsgi
      - django-asgi
    restart: on-failure
    ports:
      - 80:80/tcp
